# Page settings
baseurl = "localhost:1313"
title = "OKLAB"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "YY,Algo,utahka"
  description = "OKLAB website"
  email = "oklab.main@gmail.com"
  # Navigation
  [params.navigation]
    brand = "OKLAB"
    home = "Home"
    work = "SlideShare"
    testimonials = "Vision"
    services = "Projects"
    about = "People"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "OKLAB"
    subtitle = 'Communication and Media , Robotics Laboratory'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  #[[params.intro.item]]
  #  title = "Plan"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Get In Touch"
  #  icon = "icon-bulb"
  #  img = "img_7.jpg"

  #[[params.intro.item]]
  #  title = "Develop"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Click Me"
  #  icon = "icon-wrench"
  #  img = "img_8.jpg"

  #[[params.intro.item]]
  #  title = "Launch"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Why us?"
  #  icon = "icon-rocket"
  #  img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "SlideShare"
    #description = "説明"
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    #[[params.work.row]]
    #  img = "work_1.jpg"
    #  alt = "Image2"
    #  title = "タイトル"
    #  subtitle = "サブタイトル"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Vision"
    description = "説明"

  # Services section
  [params.services]
    enable = true
    title = "Projects"
    #description = "説明"
    
    [[params.services.item]]
      title = "音の特性を理解する"
      description = "音には多様な情報が含まれます．音の特性を理解することで，人にとってより良い環境を作り出すことができます．また音声を分析することにより認識や分類を行うことが可能になります．これらを応用することで人とロボットの円滑なコミュニケーションに繋がります．"
      icon = "icon-microphone"

    [[params.services.item]]
      title = "コミュニケーションとは何か"
      description = "人と人とのコミュニケーションの中には，言語や感情」など，様々な情報が存在しています．ロボティクスにおいても「コミュニケーションとは何か」を考えることは研究の基本的概念として必要になります．情報を分析することで，よりコミュニケーションを円滑にすることを目的としています．"
      icon = "icon-bubbles"

    [[params.services.item]]
      title = "工学的に人を支援する"
      description = "世界にはコミュニケーションを行うことが難しい人たちがたくさんいます．その人たちに，音やコミュニケーションの知見を活かしたシステムを作成することにより，手助けすることができると考えています．そこで，工学的な視点から，人を支援するシステムの開発や研究を行っています．"
      icon = "icon-graduation"

  # About section
  [params.about]
    enable = true
    title = "People"
    #description = "people"

    [[params.about.item]]
      name = "YY"
      position = "Web Designer"
      description = "説明"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-globe", "#"]
      ]

    [[params.about.item]]
      name = "Algo"
      position = "Web Developer"
      description = "説明"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "https://twitter.com/pianodwm?lang=ja"],
        ["icon-facebook", "https://www.facebook.com/profile.php?id=100007090596130"],
        ["icon-globe", "https://www.wantedly.com/users/19939464"]
      ]

    [[params.about.item]]
      name = "utahka"
      position = "Web Designer"
      description = "説明"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-globe", "#"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Contact"
    #description = "Contact"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Chiba Institute of Technology"],
        ["icon-envelope", "oklab.main@gmail.com"],
        ["icon-twitter",'<a href="https://twitter.com/_oklab_?lang=ja" target="_blank">@\_oklab\_</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
