# Page settings
baseurl = "localhost:1313"
title = "OKLAB"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "YY,Algo,utahka"
  description = "OKLAB.website"
  email = "oklab.main@gmail.com"
  # Navigation
  [params.navigation]
    brand = "OKLAB"
    home = "Home"
    work = "Vision"
    testimonials = "Pepole"
    services = "Projects"
    about = "SlideShare"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "OKLAB"
    subtitle = 'Communication , Media and Robotics Laboratory'

  # Intro section
  # Available icons: http://simplelineicons.com/
  #[params.intro]

  #[[params.intro.item]]
  #  title = "Plan"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Get In Touch"
  #  icon = "icon-bulb"
  #  img = "img_7.jpg"

  #[[params.intro.item]]
  #  title = "Develop"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Click Me"
  #  icon = "icon-wrench"
  #  img = "img_8.jpg"

  #[[params.intro.item]]
  #  title = "Launch"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Why us?"
  #  icon = "icon-rocket"
  #  img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "youtubeURL"


  # Work section
  [params.work]
    enable = true
    title = "Vision"
    description = "説明"
    #footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    #[[params.work.row]]
    #  img = "work_1.jpg"
    #  alt = "Image2"
    #  title = "Project 1"
    #  subtitle = "Branding"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "People"
    description = "author"
    
    [[params.testimonials.item]]
      name = "YY"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"]
      ]

      [[params.testimonials.item]]
      name = "Algo"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "@pianodwm"],
        ["icon-facebook", "KidaTakanari"]
      ]

      [[params.testimonials.item]]
      name = "utahka"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]
      
  # Services section
  [params.services]
    enable = true
    title = "Projects"

    [[params.services.item]]
      title = "あ"
      description = "いうえお"
      #icon = "icon-anchor"

    [[params.services.item]]
      title = "か"
      description = "きくけこ"
      #icon = "icon-layers2"
    [[params.services.item]]
      title = "さ"
      description = "しすせそ"
      #icon = "icon-video2"

  # About section
  [params.about]
    enable = false
    title = "SlideShare"
    description = "説明"

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Contact"
    description = "説明"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "場所"],
        ["icon-phone", "TEL"],
        ["icon-envelope", "mail"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
